FROM ruby:3.3.4-alpine AS dev
RUN apk add --no-cache \
        make \
        pkgconfig \
        build-base \
        autoconf \
        nodejs \
        yarn \
        mariadb-dev \
        bash # used in crontab generated by whenever

RUN mkdir /application
WORKDIR /application
COPY Gemfile /application/Gemfile
COPY Gemfile.lock /application/Gemfile.lock
RUN bundle install

# Add a script to be executed every time the container starts.
COPY docker-entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["sh", "docker-entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]

FROM dev AS prod

COPY . /application
RUN RAILS_ENV=production \
    NODE_OPTIONS=--openssl-legacy-provider \
    SECRET_KEY_BASE=placeholder \
    WJR_DATABASE_NAME=placeholder \
    WJR_DATABASE_TEST_NAME=placeholder \
    WJR_DATABASE_HOST=placeholder \
    WJR_DATABASE_USERNAME=placeholder \
    WJR_DATABASE_PASSWORD=placeholder \
    WJR_PASSWORD_SALT=placeholder \
    WJR_SECRET_BASE=placeholder \
    WJR_SECRET_TOKEN=placeholder \
    WJR_DEVISE_SECRET_KEY=placeholder \
    WJR_RECAPTCHA_SITE_KEY=placeholder \
    WJR_RECAPTCHA_SECRET_KEY=placeholder \
    WJR_SMTP_ADDRESS=placeholder \
    WJR_SMTP_DOMAIN=placeholder \
    WJR_SMTP_USER_NAME=placeholder \
    WJR_SMTP_PASSWORD=placeholder \
    WJR_DATA_FOLDER=placeholder \
    WJR_DATA_URL=placeholder \
    bundle exec rails assets:precompile
