default: &default
    secret_key_base: <%= ENV.fetch('WJR_SECRET_BASE') %>
    secret_token: <%= ENV.fetch('WJR_SECRET_TOKEN') %>

development:
    <<: *default

test:
    <<: *default

staging:
    <<: *default

production:
    <<: *default